### ISSUE TITLE
GuidedMixup Output

### ISSUE THREAD

**Issue by khawar-islam** [3neutronstar/GuidedMixup#3]
Dear @3neutronstar 

Thanks for your work. I am quite interested to visualize GuidedMixup images, to achieve this, I have added `save_image(input_var[0], f'image_epoch_{epoch}_batch_{i}.png', args.std, args.mean)` before `prec1, prec5 = accuracy(output, target, topk=(1, 5)) ` in main.py file but the output is similar to original image.
![image_epoch_0_batch_0](https://github.com/3neutronstar/GuidedMixup/assets/11488932/428bb993-9bc7-4b47-8c45-3409a520bfb1)
![image_epoch_0_batch_1](https://github.com/3neutronstar/GuidedMixup/assets/11488932/504f0429-2dd5-4add-aa1e-742b7b1549b7)

**Comment by 3neutronstar** [comment]
Dear @khawar-islam 

Thanks for your interest in my work. To visualize the GuidedMixup images, I recommend referring to the following permalink. Uncomment the line, and you can get the visualized images.
[link](https://github.com/3neutronstar/GuidedMixup/blob/fdfcb43bb10ef2021530c178495f83c96b89eafd/mixup.py#L269)

Because the variable named `input_var` is not changed by using any mixup algorithm described in `main.py`, your results are the natural outcome.

Again, thank you for your interest in our work.
